/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Stats = IDL.Record({
  'songsPlayed' : IDL.Nat,
  'activeUsers' : IDL.Nat,
  'serverCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getStats' : IDL.Func([], [Stats], ['query']),
  'updateStats' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Stats = IDL.Record({
    'songsPlayed' : IDL.Nat,
    'activeUsers' : IDL.Nat,
    'serverCount' : IDL.Nat,
  });
  
  return IDL.Service({
    'getStats' : IDL.Func([], [Stats], ['query']),
    'updateStats' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };